### PR TITLE
'use strict'; // Created by Gamepro5 @ https://gamepro5.github.io // Depends on three.js  function isTouchDevice() {   return 'ontouchstart' in document.documentElement; };  function LoadPhotosphere(equirectangularImagePath, canvasID) {    this.canvas = document.querySelector('#' + canvasID); // what id the canvas tag needs to have for it to append it to   this.canvas.style.touchAction = "none";

### PR DESCRIPTION
**Pull request by SheepTester**
@Gamepro5 @Velosify @Nichodon

### CODE REVIEW

**Comment by SheepTester** [comment]
Étienne

**Comment by Velosify** [comment]
Warm uie

**Comment by SheepTester** [comment]
Test

**Comment by SheepTester** [comment]
https://github.com/Gamepro5/untitled_game/blob/master/README.md#L1

https://github.com/Gamepro5/photosphere.js/blob/master/build/photosphere.js#L3

**Comment by SheepTester** [comment]
anematode/tech_guy#2

**Comment by SheepTester** [comment]
redundant now
```diff
diff --git a/README.md b/README.md
index 2108bee..e874a32 100644
--- a/README.md
+++ b/README.md
@@ -1 +1,3 @@
-# untitled_game
\ No newline at end of file
+# untitled_game
+
+This game is copyrighted by the Grand, the Glorious, the Extreme, the Eternal, the Magnificent, the Great Professional of the Games V. Please contact him for information about your rights to the use, modification, distribution, or exponentation of this Work.
```

**Pull request closed without merging**
